Implementation of Boron Driver
enrico-dev/enrico pull request #162
Opened 2022-03-26 19:14 UTC by nelsonag

This PR completes the critical boron search driver implementation started by @mekiel-sudo.  This capability is added with a BoronDriver class that is an attribute of the CoupledDriver class. 

This capability performs the following actions:
1. Gathers user input from the ``<neutronics>`` block of enrico.xml:
  a. The capability is enabled with the boolean ``boron_search`` element.  
  b. When enabled, the following elements apply: ``initial_boron_ppm, target_keff, target_keff_tolerance, B10_enrichment, and boron_epsilon``.
2. The HeatDriver's knowledge of which cells are fluid bearing is communicated to the BoronDriver's processors. 
3. The initial boron conditions are set or determined, depending on the setting of the ``initial_boron_ppm`` parameter.
4. For each picard iteration the following is performed:
  a. Perform neutronics and heat calcs as usual
  b. Update the boron concentration with a simple first-order slope based method based on the last two Boron ppms and k-effs in order to predict the ppm to provide the ``target_keff``. 
  c. Check convergence of the heat solver as normal, and the boron driver by ensuring the boron ppm has changed less than the specified ``boron_epsilon`` input AND that k-eff is within the user-specified target k-eff and its tolerance. A 95% CI check is used to verify the MC-based k-eff and its stochastic uncertainty is within the target k-eff window.
5. If not converged, repeat back to step 4. If converged proceed to step 6
6. Update the time step and return to step 4, as usual. However, on subsequent timesteps no boron search is performed as Boron concentration is generally an initial condition outside of longer-term depletion-type calculations.

A single rod test with thermal feedback and a boron search is included in ``tests/singlerod/openmc_boron_heat_surrogate/``.  At this point, there is no automatic checking of results. This can change based on this PR review, but this seemed consistent with existing tests (though I may be misunderstanding!).

Finally, while this is noted in the manual, it should be noted here that the Boron ppm is stated on total Boron (vice B-10) ppm on a number density basis. Further, this implementation assumes the reactivity effect of the H/O in boric acid is small and therefore this Boron search only varies the Boron concentration and not the H/O with it.

2022-04-01 16:32 UTC, paulromano requested changes
Thanks for finishing this off @nelsonag! Overall the changes look good -- see below for some modest suggestions.

@sphamil do you want to take a pass at reviewing this too?

2022-04-01 16:32 UTC, paulromano commented on tests/singlerod/openmc_boron_heat_surrogate/enrico.xml
> +    <target_keff_tolerance> 0.01 </target_keff_tolerance>
```suggestion
    <target_keff_tolerance>0.01</target_keff_tolerance>
```

2022-04-01 16:32 UTC, paulromano commented on src/openmc_driver.cpp
> +  return ppm;
```suggestion
  return N_boron / (N_boron + N_not_boron) * 1e6;
```

2022-04-01 16:32 UTC, paulromano commented on src/coupled_driver.cpp
> +    for (const auto& heat_rank : heat_ranks_) {
```suggestion
    for (auto heat_rank : heat_ranks_) {
```

2022-04-01 16:32 UTC, paulromano commented on src/coupled_driver.cpp
> +      temp_vector.clear();
Since `temp_vector` was just created, there shouldn't be a need to clear it
```suggestion
```

2022-04-01 16:32 UTC, paulromano commented on src/openmc_driver.cpp
> +  // This method gts the boron concentration from the initial conditions
```suggestion
  // This method gets the boron concentration from the initial conditions.
```

2022-04-01 16:32 UTC, paulromano commented on src/openmc_driver.cpp
> +  // addiitonal execution is only incurred once.
```suggestion
  // additional execution is only incurred once.
```

2022-04-01 16:32 UTC, paulromano commented on src/openmc_driver.cpp
> +  for (auto& cell : fluid_cell_handles) {
```suggestion
  for (auto cell : fluid_cell_handles) {
```

2022-04-07 02:31 UTC, paulromano requested changes
Thanks for the updates! A few more little things and then it should be good to go

2022-04-07 02:31 UTC, paulromano commented on src/openmc_driver.cpp
> +  return N_boron / (N_boron + N_not_boron) * 1e6;;
```suggestion
  return N_boron / (N_boron + N_not_boron) * 1e6;
```

2022-04-07 02:31 UTC, paulromano commented on src/coupled_driver.cpp
>    return converged;
```suggestion
  return heat_converged && boron_converged;
```

2022-04-07 02:31 UTC, paulromano commented on src/coupled_driver.cpp
>    bool converged;
```suggestion
```

2022-04-07 02:31 UTC, paulromano commented on include/enrico/shift_driver.h
> +  };
```suggestion
    return 0.;
  }
```

2022-04-07 02:31 UTC, paulromano commented on include/enrico/shift_driver.h
> +                     double ppm, double B10_iso_abund) const override {};
```suggestion
                     double ppm, double B10_iso_abund) const override {}
```

2022-04-07 19:27 UTC, nelsonag commented
All set @paulromano

2022-04-07 19:29 UTC, paulromano approved these changes

2022-04-07 20:18 UTC, merged